steps:
- id: 'branch-name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "Branch Name: $BRANCH_NAME"
      echo "***********************"

- id: 'tf-init'
  name: 'hashicorp/terraform:1.5.6'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd setup
      terraform init || { echo "Terraform init failed"; exit 1; }

- id: 'tf-plan'
  name: 'hashicorp/terraform:1.5.6'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd setup
      terraform plan -out=plan_output.txt || { echo "Terraform plan failed"; exit 1; }

- id: 'post-pr-comment'
  name: 'alpine:3.18'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      apk add --no-cache jq curl
      COMMENT=$(cat setup/plan_output.txt | jq -Rs .)
      curl -X POST -H "Content-Type: application/json" \
        -d '{"body":"test"}' \
        https://api.github.com/repos/mizuki4i4/${REPO_NAME}/issues/${_PR_NUMBER}/comments

# ログオプションを追加
options:
  logging: CLOUD_LOGGING_ONLY  # または NON
