steps:
- id: 'branch-name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "Branch Name: $BRANCH_NAME"
      echo "***********************"

- id: 'extract-pr-info'
  name: 'alpine:3.18' # Alpineイメージ
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      apk add --no-cache jq
      if [ ! -f /workspace/event.json ]; then
          echo "Error: event.json not found."
          exit 1
      fi

      PR_NUMBER=$(jq '.pull_request.number' /workspace/event.json)
      REPO_NAME=$(jq -r '.repository.name' /workspace/event.json)
      REPO_OWNER=$(jq -r '.repository.owner.login' /workspace/event.json)

      echo "PR_NUMBER=$PR_NUMBER" >> /workspace/env_vars
      echo "REPO_NAME=$REPO_NAME" >> /workspace/env_vars
      echo "REPO_OWNER=$REPO_OWNER" >> /workspace/env_vars

- id: 'tf-init'
  name: 'hashicorp/terraform:1.5.6'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd setup
      terraform init || { echo "Terraform init failed"; exit 1; }

- id: 'tf-plan'
  name: 'hashicorp/terraform:1.5.6'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd setup
      terraform plan -out=plan_output.txt || { echo "Terraform plan failed"; exit 1; }

- id: 'post-pr-comment'
  name: 'alpine:3.18' # Alpineイメージ
  entrypoint: 'sh'
  env:
    - 'GITHUB_TOKEN=${_GITHUB_TOKEN}'
  args:
  - '-c'
  - |
      apk add --no-cache jq
      if [ ! -f /workspace/env_vars ]; then
          echo "Error: env_vars not found."
          exit 1
      fi

      source /workspace/env_vars
      if [ ! -f setup/plan_output.txt ]; then
          echo "Error: plan_output.txt not found."
          exit 1
      fi

      COMMENT=$(cat setup/plan_output.txt | jq -Rs .)
      curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
        -H "Content-Type: application/json" \
        -d "{\"body\":${COMMENT}}" \
        https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/comments || {
          echo "Failed to post PR comment."
          exit 1
      }

# ログオプションを追加
options:
  logging: CLOUD_LOGGING_ONLY  # または NONE
