steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "Branch Name: $BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:1.5.6' # 最新安定版のイメージ
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd setup
      terraform init || exit 1

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.5.6' # 最新安定版のイメージ
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd setup
      terraform plan || exit 1
# [END tf-plan]

# ログオプションを追加
options:
  logging: CLOUD_LOGGING_ONLY  # または NONE
